### PR TITLE
Prometheus auth type environment variable

### PR DESCRIPTION
**Pull request by pawelchaniewski**
MinIO supports two authentication modes for Prometheus either jwt or public, by default MinIO runs in jwt mode. To allow public access without authentication for prometheus metrics set you must set MINIO_PROMETHEUS_AUTH_TYPE environment variable to "public".

This is crucial if you want to use for example bosh service discovery or monitor all nodes in cluster without having to hardcode dns names or ip adresses.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@pawelchaniewski you can set env variables through properties: https://github.com/minio/minio-boshrelease/blob/master/jobs/minio-server/spec
```
  envs:
    description: "environmental variable settings for MinIO process"
    default: ""
    example: |
      export MINIO_STORAGE_CLASS_STANDARD=EC:2
      export MINIO_BROWSER=off
```

**Comment by pawelchaniewski** [comment]
Ok, but i want to use this release without having to make my own release, so i think changing the spec and template is the best option. Am i wrong? My use case is I want to use your release to deploy minio on my BOSH.

**Comment by patrickcrocker** [comment]
@pawelchaniewski The spec and template already support this.  You just need to export your environment variables using the `envs` option.  Take a look at [my manifest here](https://github.com/patrickcrocker/bosh-ops/blob/master/deployments/minio/minio.yml#L14) for an example.

**Comment by pawelchaniewski** [comment]
Yes, You are right! Thanks! :D

**Pull request closed without merging**
