### PR TITLE
Allow Operator to configure cluster to use HTTPS

### PR DESCRIPTION
**Pull request by ljfranklin**
- Adds optional BOSH manifest properties: `server_cert`, `server_key`,
  `ca_cert`, and `dns_alias`
- If a cert is specified, nodes in the cluster will use HTTPS to
  communicate with each other
- `dns_alias` is a temporary hack to allow us to generate certs that are
  compatible with BOSH DNS. It's hard to know the BOSH DNS hostnames
  ahead of time (e.g.
  NODE_ID.INSTANCE_GROUP.NETWORK_NAME.DEPLOYMENT.bosh), this property
  allows the cluster to use a fixed name like
  `minio-server.service.cf.internal` to make it easy to generate a cert
  with the right hostnames. In the future BOSH has a feature planned to
  generate certs for you.

Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
thanks @ljfranklin for the PR

**Comment by Proplex** [comment]
Am I mistaken, or does this commit now make `smoke-tests` fail because `smoke-tests` is hard-coded to use HTTP to access the Minio instance(s)?

**Comment by ljfranklin** [comment]
@Proplex still uses `http` by default. If you specify the optional `server_cert` property the cluster will use HTTPS instead.

**Comment by ljfranklin** [comment]
Oh, nvm I understand what you're saying. Good question, if you specify a TLS cert does Minio refuse HTTP connections? The smoke test job didn't exist when I submitted the PR so I couldn't run them.

**Comment by Proplex** [comment]
Minio refuses to accept HTTP traffic if certs are present. My smoke tests are currently failing with `Access Denied`, because Minio returns `403 - SSL Required` when accessing over HTTP with certs present.

**Comment by krishnasrinivas** [comment]
we'll fix it @Proplex thanks for bringing it to our attention.

**Pull request merged**
